name: "App Gateway Front Door Demo Images Deployment"
on:
  push:
    paths:
      - 'AppGwFrontDoorDemo.Images'
      - '.github/workflows/app-gw-front-door-demo-images-deploy.yml'
    branches: 
      - main

jobs:
  build-and-deploy:
    env:
        PROJECT_PATH: './AppGwFrontDoorDemo.Images/AppGwFrontDoorDemo.Images.csproj'
        WEB_APP: app-gw-front-door-demo-images-jaspecla
    runs-on: self-hosted
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # authenticate to Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302 # Replace with specific dotnet core version

    
    # dotnet build, test, and publish
    - name: dotnet build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release
    - name: dotnet test
      run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/appgwimg 

    - name: 'Run Azure webapp deploy action'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.WEB_APP }}
        package: ${{ env.DOTNET_ROOT }}/appgwimg
